/**
 * Pull request tools for the github plugin.
 *
 * Ten tools covering PR lifecycle (create/update/get/list/find) and
 * PR content inspection (files, commits, diff stats). All PR-creation tools
 * auto-detect repo and branch via cross-plugin `get_git_context`.
 */

import { z } from "zod";
import { defineTool, type ToolDefinition } from "../../types.js";
import { getClient } from "../state.js";
import { resolveRepository, getGitContextSafe } from "../shared.js";
import type { CommitInfo, DiffStats } from "../types.js";

// ============================================================================
// Private helper — PR description generator
// ============================================================================

interface PRDescriptionContext {
  commits: CommitInfo[];
  diffStats: DiffStats;
  userContext?: string;
  sourceBranch: string;
  targetBranch: string;
}

function generatePRDescription(ctx: PRDescriptionContext): string {
  const { commits, diffStats, userContext, sourceBranch, targetBranch } = ctx;
  const sections: string[] = [];

  sections.push("## 📋 Description");
  if (userContext && userContext.trim()) {
    sections.push(userContext.trim());
  } else {
    sections.push(
      `This PR merges \`${sourceBranch}\` into \`${targetBranch}\`.`,
    );
  }

  sections.push("");
  sections.push("## 📊 Changes");
  sections.push(`- **Files changed:** ${diffStats.changedFiles}`);
  sections.push(`- **Additions:** +${diffStats.additions}`);
  sections.push(`- **Deletions:** -${diffStats.deletions}`);

  if (commits.length > 0) {
    sections.push("");
    sections.push("## 📝 Commits");
    commits.slice(0, 10).forEach((commit) => {
      const message = commit.message.split("\n")[0] ?? "";
      sections.push(`- \`${commit.sha.slice(0, 7)}\` ${message}`);
    });
    if (commits.length > 10) {
      sections.push(`- ... and ${commits.length - 10} more commits`);
    }
  }

  sections.push("");
  sections.push("## ✅ Checklist");
  sections.push("- [ ] Code has been tested");
  sections.push("- [ ] Documentation updated (if needed)");
  sections.push("- [ ] No breaking changes (or documented if any)");

  sections.push("");
  sections.push("---");
  sections.push(
    "*Generated by [Kuzo MCP](https://github.com/seantokuzo/seantokuzo-mcp) 🚀*",
  );

  return sections.join("\n");
}

// ============================================================================
// Shared schema fragments
// ============================================================================

const repositoryField = z
  .string()
  .optional()
  .describe(
    "Repository as owner/repo, full GitHub URL, or just the repo name if GITHUB_USERNAME is set. Auto-detected from the current git repo if omitted.",
  );

// ============================================================================
// create_pull_request
// ============================================================================

const createPRSchema = z.object({
  repository: repositoryField,
  source_branch: z
    .string()
    .optional()
    .describe(
      "The branch with the changes. Auto-detected as the current branch if omitted.",
    ),
  target_branch: z
    .string()
    .optional()
    .describe(
      "The branch to merge into. Auto-detected as the default branch (main/master) if omitted.",
    ),
  title: z
    .string()
    .optional()
    .describe("PR title. If omitted, generated from the first commit message."),
  description: z
    .string()
    .optional()
    .describe(
      "The FULL PR description. When the user provides brief notes, expand them into a comprehensive description before calling this tool.",
    ),
  draft: z
    .boolean()
    .optional()
    .default(false)
    .describe("Whether to create as a draft PR"),
});

const createPullRequestTool = defineTool({
  name: "create_pull_request",
  description: `Create a new GitHub pull request.

TIP: Repo, source branch, and target branch are all auto-detected from the current git context if not provided. Call \`get_git_context\` first if you want to show the user what will be used.

AI-Enhanced Descriptions: When the user provides brief notes about their changes, YOU (Claude) should expand those into a comprehensive PR description BEFORE calling this tool. Include:
- A clear summary of what the PR does and why
- Key implementation details
- Breaking changes or migration notes
- Testing considerations

The 'description' parameter should contain the FULL description you generate — the tool will format it with headers and stats.`,
  inputSchema: createPRSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo, source: repoSource } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );
    const fullRepo = `${repo.owner}/${repo.repo}`;

    const gitData = await getGitContextSafe(context);
    const sourceBranch = input.source_branch ?? gitData?.currentBranch ?? null;

    // Resolve target branch in priority order:
    //   1. Explicit input
    //   2. git-context defaultBranch (from local git remote HEAD)
    //   3. GitHub API repo.default_branch (authoritative — handles `master`
    //      and custom default branches for repos with no local clone)
    let targetBranch: string;
    let targetBranchSource: string;
    if (input.target_branch) {
      targetBranch = input.target_branch;
      targetBranchSource = "provided";
    } else if (gitData?.defaultBranch) {
      targetBranch = gitData.defaultBranch;
      targetBranchSource = "auto-detected (git default branch)";
    } else {
      const info = await client.getRepoInfo(repo);
      targetBranch = info.default_branch;
      targetBranchSource = "auto-detected (GitHub default_branch)";
    }

    const resolved = {
      repository: { value: fullRepo, source: repoSource },
      sourceBranch: {
        value: sourceBranch,
        source: input.source_branch
          ? "provided"
          : "auto-detected (current branch)",
      },
      targetBranch: {
        value: targetBranch,
        source: targetBranchSource,
      },
    };

    if (!sourceBranch) {
      throw new Error(
        "Could not determine source branch. Please specify source_branch.",
      );
    }
    if (sourceBranch === targetBranch) {
      throw new Error(
        `Source branch (${sourceBranch}) and target branch (${targetBranch}) are the same. Cannot create PR.`,
      );
    }

    const existingPR = await client.findPRForBranch(repo, sourceBranch);
    if (existingPR) {
      return {
        success: false,
        message: `A PR already exists for branch ${sourceBranch}`,
        resolved,
        data: {
          existingPR: {
            number: existingPR.number,
            title: existingPR.title,
            url: existingPR.html_url,
          },
        },
      };
    }

    // Commits/diff stats feed the PR description generator. If the compare
    // call fails (rare — usually transient or rate-limited), degrade
    // gracefully with a minimal description rather than failing the whole
    // PR creation. The client methods themselves throw so direct tool calls
    // (get_diff_stats, get_changed_files) still surface errors loudly.
    let commits: CommitInfo[] = [];
    let diffStats: DiffStats = { additions: 0, deletions: 0, changedFiles: 0 };
    try {
      commits = await client.getCommitsBetween(
        repo,
        targetBranch,
        sourceBranch,
      );
      diffStats = await client.getDiffStats(
        repo,
        targetBranch,
        sourceBranch,
      );
    } catch (err) {
      context.logger.warn(
        "Could not fetch commits/diff for PR description — creating with minimal description",
        err,
      );
    }

    const title =
      input.title ??
      commits[0]?.message.split("\n")[0] ??
      `Merge ${sourceBranch} into ${targetBranch}`;

    const body = generatePRDescription({
      commits,
      diffStats,
      userContext: input.description,
      sourceBranch,
      targetBranch,
    });

    const pr = await client.createPullRequest({
      repo,
      title,
      body,
      head: sourceBranch,
      base: targetBranch,
      draft: input.draft,
    });

    return {
      success: true,
      message: `🚀 Created PR #${pr.number}: ${pr.title}`,
      resolved,
      data: {
        number: pr.number,
        title: pr.title,
        url: pr.html_url,
        state: pr.state,
        draft: pr.draft,
        repository: fullRepo,
        sourceBranch,
        targetBranch,
        commits: commits.length,
        filesChanged: diffStats.changedFiles,
        additions: diffStats.additions,
        deletions: diffStats.deletions,
      },
    };
  },
});

// ============================================================================
// update_pull_request
// ============================================================================

const updatePRSchema = z.object({
  repository: repositoryField,
  pull_number: z
    .number()
    .int()
    .min(1)
    .optional()
    .describe(
      "The PR number to update. If omitted, auto-detected by finding the open PR for the current branch.",
    ),
  title: z.string().optional().describe("New title for the PR"),
  description: z
    .string()
    .optional()
    .describe("New description — or additional context when appending"),
  append_to_existing: z
    .boolean()
    .optional()
    .default(false)
    .describe(
      "If true, append the new description to the existing body instead of replacing it.",
    ),
});

const updatePullRequestTool = defineTool({
  name: "update_pull_request",
  description: `Update an existing pull request's title and/or description.

TIP: If the user doesn't specify a PR number, this tool auto-detects the PR for the current branch. Use this when the user wants to improve a PR description or update it after pushing new changes.`,
  inputSchema: updatePRSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo, source: repoSource } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );
    const fullRepo = `${repo.owner}/${repo.repo}`;

    let pullNumber = input.pull_number;
    let prSource = "provided";
    if (!pullNumber) {
      const gitData = await getGitContextSafe(context);
      const branch = gitData?.currentBranch;
      if (!branch) {
        throw new Error(
          "No PR number specified and could not determine current branch.",
        );
      }
      const pr = await client.findPRForBranch(repo, branch);
      if (!pr) {
        throw new Error(
          `No open PR found for branch ${branch}. Please specify pull_number.`,
        );
      }
      pullNumber = pr.number;
      prSource = `auto-detected from branch ${branch}`;
    }

    const resolved = {
      repository: { value: fullRepo, source: repoSource },
      pullNumber: { value: pullNumber, source: prSource },
    };

    const currentPR = await client.getPullRequest(repo, pullNumber);

    // Body update logic:
    //   - append_to_existing=true + description given → append update section
    //     to currentPR.body (treating null body as empty string)
    //   - append_to_existing=true + no description → no body change
    //   - append_to_existing=false + description given → regenerate full body
    //     from commits + description (replace mode)
    //   - append_to_existing=false + no description → title-only update,
    //     leave body untouched so we don't wipe a hand-written description
    let newBody: string | undefined;
    const updateDescription = input.description?.trim() ?? "";

    if (input.append_to_existing) {
      if (updateDescription) {
        const existingBody = currentPR.body ?? "";
        newBody =
          existingBody +
          (existingBody ? "\n\n---\n\n" : "") +
          "## 📝 Update\n\n" +
          updateDescription;
      }
      // else: leave newBody undefined → Octokit won't touch the body
    } else if (updateDescription) {
      const commits = await client.getPRCommits(repo, pullNumber);
      newBody = generatePRDescription({
        commits,
        diffStats: {
          additions: currentPR.additions,
          deletions: currentPR.deletions,
          changedFiles: currentPR.changed_files,
        },
        userContext: input.description,
        sourceBranch: currentPR.head.ref,
        targetBranch: currentPR.base.ref,
      });
    }
    // else: title-only update path → newBody stays undefined

    const pr = await client.updatePullRequest({
      repo,
      pullNumber,
      title: input.title,
      body: newBody,
    });

    return {
      success: true,
      message: `✏️ Updated PR #${pr.number}`,
      resolved,
      data: {
        number: pr.number,
        title: pr.title,
        url: pr.html_url,
        repository: fullRepo,
        sourceBranch: currentPR.head.ref,
        targetBranch: currentPR.base.ref,
      },
    };
  },
});

// ============================================================================
// get_pull_request
// ============================================================================

const getPRSchema = z.object({
  repository: repositoryField,
  pull_number: z.number().int().min(1).describe("The PR number to fetch"),
});

const getPullRequestTool = defineTool({
  name: "get_pull_request",
  description: "Get details about a specific pull request by number.",
  inputSchema: getPRSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo, source: repoSource } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );
    const fullRepo = `${repo.owner}/${repo.repo}`;

    const pr = await client.getPullRequest(repo, input.pull_number);

    return {
      success: true,
      resolved: {
        repository: { value: fullRepo, source: repoSource },
        pullNumber: { value: input.pull_number, source: "provided" },
      },
      data: {
        number: pr.number,
        title: pr.title,
        body: pr.body,
        state: pr.state,
        draft: pr.draft,
        url: pr.html_url,
        repository: fullRepo,
        sourceBranch: pr.head.ref,
        targetBranch: pr.base.ref,
        author: pr.user?.login,
        additions: pr.additions,
        deletions: pr.deletions,
        changedFiles: pr.changed_files,
        createdAt: pr.created_at,
        updatedAt: pr.updated_at,
      },
    };
  },
});

// ============================================================================
// list_pull_requests
// ============================================================================

const listPRsSchema = z.object({
  repository: repositoryField,
  state: z
    .enum(["open", "closed", "all"])
    .optional()
    .default("open")
    .describe("Filter by PR state"),
});

const listPullRequestsTool = defineTool({
  name: "list_pull_requests",
  description: "List pull requests for a repository (default: open PRs).",
  inputSchema: listPRsSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo, source: repoSource } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );
    const fullRepo = `${repo.owner}/${repo.repo}`;

    const prs = await client.listPullRequests(repo, input.state);

    return {
      success: true,
      message: `Found ${prs.length} ${input.state} PR(s)`,
      resolved: {
        repository: { value: fullRepo, source: repoSource },
        state: { value: input.state, source: "provided (default: open)" },
      },
      data: prs.map((pr) => ({
        number: pr.number,
        title: pr.title,
        state: pr.state,
        draft: pr.draft,
        url: pr.html_url,
        sourceBranch: pr.head.ref,
        targetBranch: pr.base.ref,
        author: pr.user?.login,
      })),
    };
  },
});

// ============================================================================
// find_pr_for_branch
// ============================================================================

const findPRSchema = z.object({
  repository: repositoryField,
  branch: z
    .string()
    .optional()
    .describe("The branch name to find a PR for. Auto-detected if omitted."),
});

const findPRForBranchTool = defineTool({
  name: "find_pr_for_branch",
  description:
    "Find the open pull request associated with a specific branch. Useful to check whether a PR already exists.",
  inputSchema: findPRSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo, source: repoSource } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );
    const fullRepo = `${repo.owner}/${repo.repo}`;

    let branch = input.branch;
    let branchSource = "provided";
    if (!branch) {
      const gitData = await getGitContextSafe(context);
      branch = gitData?.currentBranch ?? undefined;
      branchSource = "auto-detected (current branch)";
    }

    if (!branch) {
      throw new Error(
        "No branch specified and could not determine current branch.",
      );
    }

    const resolved = {
      repository: { value: fullRepo, source: repoSource },
      branch: { value: branch, source: branchSource },
    };

    const pr = await client.findPRForBranch(repo, branch);

    if (!pr) {
      return {
        success: true,
        message: `No open PR found for branch ${branch}`,
        resolved,
        data: null,
      };
    }

    return {
      success: true,
      message: `Found PR #${pr.number} for branch ${branch}`,
      resolved,
      data: {
        number: pr.number,
        title: pr.title,
        url: pr.html_url,
        state: pr.state,
        repository: fullRepo,
      },
    };
  },
});

// ============================================================================
// get_pr_files
// ============================================================================

const getPRFilesSchema = z.object({
  repository: repositoryField,
  pull_number: z.number().int().min(1).describe("The PR number"),
});

const getPRFilesTool = defineTool({
  name: "get_pr_files",
  description:
    "Get the list of files changed in a pull request (filename, status, additions, deletions). Use `get_pr_files_with_patch` if you also need the actual diff content.",
  inputSchema: getPRFilesSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );

    const files = await client.getPRFiles(repo, input.pull_number);

    return {
      success: true,
      message: `Found ${files.length} file(s) in PR #${input.pull_number}`,
      data: files,
    };
  },
});

// ============================================================================
// get_pr_files_with_patch
// ============================================================================

const getPRFilesWithPatchTool = defineTool({
  name: "get_pr_files_with_patch",
  description:
    "Get PR files including the full diff/patch content for each file. Use this when you need to actually read the code changes (e.g. for code review).",
  inputSchema: getPRFilesSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );

    const files = await client.getPRFilesWithPatch(repo, input.pull_number);

    return {
      success: true,
      message: `Found ${files.length} file(s) with patches in PR #${input.pull_number}`,
      data: files,
    };
  },
});

// ============================================================================
// get_pr_commits
// ============================================================================

const getPRCommitsTool = defineTool({
  name: "get_pr_commits",
  description: "Get the commit history for a specific pull request.",
  inputSchema: getPRFilesSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );

    const commits = await client.getPRCommits(repo, input.pull_number);

    return {
      success: true,
      message: `PR #${input.pull_number} has ${commits.length} commit(s)`,
      data: commits,
    };
  },
});

// ============================================================================
// get_changed_files (between refs)
// ============================================================================

const getChangedFilesSchema = z.object({
  repository: repositoryField,
  base: z.string().describe("Base ref (branch, tag, or SHA) to compare from"),
  head: z.string().describe("Head ref (branch, tag, or SHA) to compare to"),
});

const getChangedFilesTool = defineTool({
  name: "get_changed_files",
  description:
    "List files changed between two refs (branches, tags, or SHAs). Useful for previewing what a PR would contain before creating it.",
  inputSchema: getChangedFilesSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );

    const files = await client.getChangedFiles(repo, input.base, input.head);

    return {
      success: true,
      message: `${files.length} file(s) changed between ${input.base}...${input.head}`,
      data: files,
    };
  },
});

// ============================================================================
// get_diff_stats (between refs)
// ============================================================================

const getDiffStatsTool = defineTool({
  name: "get_diff_stats",
  description:
    "Get aggregate diff stats (additions, deletions, changed files) between two refs.",
  inputSchema: getChangedFilesSchema,
  handler: async (input, context) => {
    const client = getClient();

    const { repo } = await resolveRepository(
      context,
      input.repository,
      client.defaultOwner,
    );

    const stats = await client.getDiffStats(repo, input.base, input.head);

    return {
      success: true,
      message: `+${stats.additions}/-${stats.deletions} across ${stats.changedFiles} file(s) between ${input.base}...${input.head}`,
      data: stats,
    };
  },
});

// ============================================================================
// Export
// ============================================================================

export const pullRequestTools: ToolDefinition[] = [
  createPullRequestTool,
  updatePullRequestTool,
  getPullRequestTool,
  listPullRequestsTool,
  findPRForBranchTool,
  getPRFilesTool,
  getPRFilesWithPatchTool,
  getPRCommitsTool,
  getChangedFilesTool,
  getDiffStatsTool,
];
