/**
 * ⚙️ Config Commands
 * Setup and verify configuration
 */

import inquirer from "inquirer";
import chalk from "chalk";
import { existsSync, writeFileSync, readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { GitHubClient } from "../../plugins/github/client.js";
import {
  showBanner,
  showSuccess,
  showError,
  showInfo,
  showBox,
  showConfigStatus,
  createStyledSpinner,
} from "../ui/display.js";

type Personality = "professional" | "chaotic" | "zen";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const envPath = resolve(__dirname, "../../../.env");

/**
 * Interactive setup wizard
 */
export async function setupInteractive(): Promise<void> {
  showBanner();

  showBox(
    [
      chalk.bold("Welcome to the Kuzo MCP Setup Wizard! 🧙‍♂️"),
      "",
      "Let's get you configured and ready to automate some PRs.",
      "",
      chalk.yellow("You'll need:"),
      "  • A GitHub Personal Access Token (PAT)",
      "  • Your GitHub username",
    ].join("\n"),
    { title: "🚀 Setup", borderColor: "cyan" },
  );

  // Check if .env exists
  const envExists = existsSync(envPath);
  const existingEnv: Record<string, string> = {};

  if (envExists) {
    const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([
      {
        type: "confirm",
        name: "overwrite",
        message: ".env file already exists. Overwrite?",
        default: false,
      },
    ]);

    if (!overwrite) {
      showInfo("Setup cancelled. Your existing .env is preserved.");
      return;
    }

    // Parse existing .env to use as defaults
    try {
      const content = readFileSync(envPath, "utf-8");
      content.split("\n").forEach((line) => {
        const [key, ...valueParts] = line.split("=");
        if (key && !key.startsWith("#")) {
          existingEnv[key.trim()] = valueParts.join("=").trim();
        }
      });
    } catch {
      // Ignore parse errors
    }
  }

  // Prompt for configuration
  const answers = await inquirer.prompt<{
    githubToken: string;
    githubUsername: string;
    personality: Personality;
    baseBranch: string;
    draftPRs: boolean;
  }>([
    {
      type: "password",
      name: "githubToken",
      message: "🔑 GitHub Personal Access Token:",
      mask: "*",
      validate: (input: string) => {
        if (!input) return "Token is required";
        if (!input.startsWith("ghp_") && !input.startsWith("github_pat_")) {
          return "Token should start with ghp_ or github_pat_";
        }
        return true;
      },
    },
    {
      type: "input",
      name: "githubUsername",
      message: "👤 GitHub Username:",
      default: existingEnv["GITHUB_USERNAME"] || "",
      validate: (input: string) => input.length > 0 || "Username is required",
    },
    {
      type: "list",
      name: "personality",
      message: "🎭 CLI Personality:",
      choices: [
        { name: "🔥 Chaotic - Fun, energetic, memes", value: "chaotic" },
        { name: "💼 Professional - Clean, minimal", value: "professional" },
        { name: "🧘 Zen - Calm, philosophical", value: "zen" },
      ],
      default: existingEnv["CLI_PERSONALITY"] || "chaotic",
    },
    {
      type: "input",
      name: "baseBranch",
      message: "🌿 Default base branch for PRs:",
      default: existingEnv["DEFAULT_PR_BASE_BRANCH"] || "main",
    },
    {
      type: "confirm",
      name: "draftPRs",
      message: "📝 Create PRs as drafts by default?",
      default: existingEnv["DEFAULT_PR_DRAFT"] === "true" || false,
    },
  ]);

  // Generate .env content
  const envContent = `# 🔐 GitHub Configuration
# Generated by Kuzo MCP Setup Wizard
GITHUB_TOKEN=${answers.githubToken}
GITHUB_USERNAME=${answers.githubUsername}

# 🎨 CLI Preferences
CLI_PERSONALITY=${answers.personality}

# 📝 Default PR Settings
DEFAULT_PR_BASE_BRANCH=${answers.baseBranch}
DEFAULT_PR_DRAFT=${answers.draftPRs}
`;

  // Write .env file
  try {
    writeFileSync(envPath, envContent, "utf-8");
    showSuccess(".env file created successfully!");
  } catch (error) {
    showError(
      "Failed to write .env file",
      error instanceof Error ? error.message : "Unknown error",
    );
    return;
  }

  // Verify the configuration works
  const spinner = createStyledSpinner("Verifying GitHub connection");
  spinner.start();

  try {
    // Use the token the user just entered — no need to mutate process.env
    const github = new GitHubClient({
      token: answers.githubToken,
      username: answers.githubUsername,
    });
    const connection = await github.verifyConnection();

    if (connection.valid) {
      spinner.success({
        text: `Connected to GitHub as ${chalk.cyan(connection.username)}`,
      });

      showBox(
        [
          chalk.green("✓ Setup complete!"),
          "",
          "You can now use Kuzo MCP to:",
          `  ${chalk.cyan("kuzo pr create")}  - Create a new PR`,
          `  ${chalk.cyan("kuzo pr update")}  - Update a PR description`,
          `  ${chalk.cyan("kuzo pr list")}    - List PRs`,
          `  ${chalk.cyan("kuzo config status")}  - Check config`,
          "",
          chalk.gray("Run kuzo --help for more commands"),
        ].join("\n"),
        { title: "🎉 Ready to Rock!", borderColor: "green" },
      );
    } else {
      spinner.error({ text: "GitHub connection failed" });
      showError("Could not verify GitHub connection", connection.error);
      showInfo("Your .env was saved. Please verify your token and try again.");
    }
  } catch (error) {
    spinner.error({ text: "Verification failed" });
    showError(
      "Connection test failed",
      error instanceof Error ? error.message : "Unknown error",
    );
  }
}

/**
 * Show current config status
 */
export async function showStatus(): Promise<void> {
  showBanner();

  const githubToken = process.env["GITHUB_TOKEN"] ?? "";
  const githubUsername = process.env["GITHUB_USERNAME"] ?? "";
  const configured = !!githubToken && !!githubUsername;

  if (!configured) {
    showConfigStatus(false);
    return;
  }

  // Verify connection
  const spinner = createStyledSpinner("Checking GitHub connection");
  spinner.start();

  try {
    const github = new GitHubClient({
      token: githubToken,
      username: githubUsername,
    });
    const connection = await github.verifyConnection();

    if (connection.valid) {
      spinner.success({ text: "GitHub connected" });
      showConfigStatus(true, connection.username);

      // Show additional config info
      const rawPersonality = process.env["CLI_PERSONALITY"] ?? "chaotic";
      const personality: Personality = (
        ["professional", "chaotic", "zen"] as const
      ).includes(rawPersonality as Personality)
        ? (rawPersonality as Personality)
        : "chaotic";
      const baseBranch = process.env["DEFAULT_PR_BASE_BRANCH"] ?? "main";
      const draft = process.env["DEFAULT_PR_DRAFT"] === "true";

      showBox(
        [
          chalk.bold("Current Settings:"),
          "",
          `${chalk.gray("Personality:")} ${personality}`,
          `${chalk.gray("Default Base Branch:")} ${baseBranch}`,
          `${chalk.gray("Draft PRs by Default:")} ${draft ? "Yes" : "No"}`,
        ].join("\n"),
        { title: "⚙️ Settings", borderColor: "blue" },
      );
    } else {
      spinner.error({ text: "Connection failed" });
      showError("GitHub authentication failed", connection.error);
    }
  } catch (error) {
    spinner.error({ text: "Check failed" });
    showError(
      "Failed to verify configuration",
      error instanceof Error ? error.message : "Unknown error",
    );
  }
}

export default {
  setupInteractive,
  showStatus,
};
